name: api
namespace: apis
replicas: 2
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

containerPort: 8000

service:
  port: 80
  targetPort: 8000

probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 20

resources:
  requests:
    cpu: "100m"
    memory: "120Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"
