apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: apis

spec:
  replicas: 3

  selector:
    matchLabels:
      app: order-api

  template:
    metadata:
      labels:
        app: order-api

    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: order-api
          image: ghcr.io/sachinsingh2468/order-api:v1.1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "120Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
