pipeline {

    agent any

    stages {

        stage('Kubernetes Connection Test') {

            steps {

                withCredentials([file(
			credentialsId: 'kubeconfig-prod',
                        variable: 'KUBECONFIG'
                    )
                ]) {

                    sh '''
                        echo "Testing Jenkins -> Kubernetes connection..."

                        kubectl --kubeconfig="$KUBECONFIG" get nodes

                        echo "Testing namespace access..."

                        kubectl --kubeconfig="$KUBECONFIG" get deployments -n apis

                        echo "Testing deployment permission..."

                        kubectl --kubeconfig="$KUBECONFIG" auth can-i update deployments -n apis
                    '''
                }
            }
        }
    }
}
